//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AniBaseFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anime
    {
        public int ID { get; set; }
        public string URL { get; set; }
        public string IMGURL { get; set; }
        public string TITLE { get; set; }
        public string AIRING { get; set; }
        public string DESCRIPTION { get; set; }
        public string TYPE { get; set; }
        public long EPISODES { get; set; }
        public decimal SCORE { get; set; }
        public Nullable<System.DateTime> SDATE { get; set; }
        public Nullable<System.DateTime> EDATE { get; set; }
    }
}
